name: Tests on PR

on:
  push:
    branches:
      - main
      - cookie
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Check out diffpy.srreal
        uses: actions/checkout@v4

      - name: Initialize miniconda without environment.yml
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
      - name: Configure conda channels
        run: |
          conda config --add channels conda-forge
      - name: Create conda environment and install dependencies
        run: |
          conda create -n test python=${{ matrix.python-version }} -y
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate test
          conda config --set always_yes yes --set changeps1 no
          conda install --file requirements/conda.txt -y
          conda install --file requirements/test.txt -y
          python -m pip install . --no-deps

      - name: Run tests
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate test
          pytest tests
